In [70]:
import os, sys
%pylab inline
import pandas as pd
import pickle
from importlib import reload

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

/camp/home/tootoos/working/tootoos/conda-envs/numpyro-env/lib/python3.10/site-packages/IPython/core/magics/pylab.py:166: UserWarning: pylab import has clobbered these variables: ['f', 'cla']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +

In [101]:
from glom_io_transform import paths
from glom_io_transform.data import odours; reload(odours)

In [20]:
match_file = os.path.join(paths.data_root, "matched_IO_glom.csv")
assert os.path.exists(match_file), f"File not found: {match_file}"
matched_df = pd.read_csv(match_file, delimiter=";")
matched_df

,match_id,input_row,output_row,input_exp,output_exp,distance,correlation
0,1,0,39,C592,C470,22.599.582,0.453562
1,2,2,113,C592,C525,11.258.304,0.673008
2,3,3,33,C592,C470,7.708.951,0.419286
3,4,7,110,C592,C525,0.000000,0.696483
4,5,8,114,C592,C525,19.196.192,0.587893
5,6,15,136,C592,C531,17.184.062,0.382656
6,7,16,18,C592,C450,17.709.645,0.301642
7,8,20,43,C592,C476,15.609.333,0.322390
8,9,35,159,C592,C537,16.342.217,0.426633
9,10,45,97,C598,C519,22.114.574,0.511400
10,11,50,17,C598,C450,14.294.144,0.339138
11,12,51,111,C598,C525,8.498.910,0.588918
12,13,59,0,C598,C444,0.000000,0.530443
13,14,65,148,C598,C531,15.476.136,0.556860
14,15,66,19,C598,C450,7.802.480,0.324774
15,16,68,109,C598,C519,10.031.072,0.301425

In [28]:
resps_file = os.path.join(paths.data_root, "X0Y0_new.p")
with open(resps_file, "rb") as f:
    data = pickle.load(f)

In [99]:
X = np.vstack([Xi.mean(axis=-1) for Xi in data["X0"]])
Y = np.vstack([Yi.mean(axis=-1) for Yi in data["Y0"]])

In [108]:
Xi = X[matched_df.input_row]
Yi = Y[matched_df.output_row]
corrs = [np.corrcoef(Xi[i], Yi[i])[0, 1] for i in range(len(Xi))]
matched_df["corr_sina"] = corrs
matched_df

,match_id,input_row,output_row,input_exp,output_exp,distance,correlation,corr_sina
0,1,0,39,C592,C470,22.599.582,0.453562,0.263478
1,2,2,113,C592,C525,11.258.304,0.673008,0.673600
2,3,3,33,C592,C470,7.708.951,0.419286,0.389310
3,4,7,110,C592,C525,0.000000,0.696483,0.684429
4,5,8,114,C592,C525,19.196.192,0.587893,0.446966
5,6,15,136,C592,C531,17.184.062,0.382656,0.211661
6,7,16,18,C592,C450,17.709.645,0.301642,0.384484
7,8,20,43,C592,C476,15.609.333,0.322390,0.216565
8,9,35,159,C592,C537,16.342.217,0.426633,0.468571
9,10,45,97,C598,C519,22.114.574,0.511400,0.547320
10,11,50,17,C598,C450,14.294.144,0.339138,0.374094
11,12,51,111,C598,C525,8.498.910,0.588918,0.673151
12,13,59,0,C598,C444,0.000000,0.530443,0.451341
13,14,65,148,C598,C531,15.476.136,0.556860,0.591503
14,15,66,19,C598,C450,7.802.480,0.324774,0.382794
15,16,68,109,C598,C519,10.031.072,0.301425,0.294735